//VIRTUAL CARD CONSTANTS
export const FETCH_CURRENTCARD_SUCCESS = 'FETCH_CURRENTCARD_SUCCESS';
export const FETCH_CURRENTCARD_PENDING = 'FETCH_CURRENTCARD_PENDING';
export const FETCH_CURRENTCARD_FAILURE = 'FETCH_CURRENTCARD_FAILURE';

export const SEND_NEWVC_DATA_SUCCESS = 'SEND_NEWVC_DATA_SUCCESS';
export const SEND_NEWVC_DATA_PENDING = 'SEND_NEWVC_DATA_PENDING';
export const SEND_NEWVC_DATA_FAILURE = 'SEND_NEWVC_DATA_FAILURE';


export const FETCH_CARD_DATA_SUCCESS = 'FETCH_CARD_DATA_SUCCESS';
export const FETCH_CARD_DATA_PENDING = 'FETCH_CARD_DATA_PENDING';
export const FETCH_CARD_DATA_FAILURE = 'FETCH_CARD_DATA_FAILURE';


export const SEND_TOPUP_DATA_SUCCESS = 'SEND_TOPUP_DATA_SUCCESS';
export const SEND_TOPUP_DATA_PENDING = 'SEND_TOPUP_DATA_PENDING';
export const SEND_TOPUP_DATA_FAILURE = 'SEND_TOPUP_DATA_FAILURE';

export const LIQUIDATE_CARD_SUCCESS = 'LIQUIDATE_CARD_SUCCESS';
export const LIQUIDATE_CARD_PENDING = 'LIQUIDATE_CARD_PENDING';
export const LIQUIDATE_CARD_FAILURE = 'LIQUIDATE_CARD_FAILURE';

export const CHANGEACTIVESTATUS_VIRTUAL_SUCCESS = 'CHANGEACTIVESTATUS_VIRTUAL_SUCCESS';
export const CHANGEACTIVESTATUS_VIRTUAL_PENDING = 'CHANGEACTIVESTATUS_VIRTUAL_PENDING';
export const CHANGEACTIVESTATUS_VIRTUAL_FAILURE = 'CHANGEACTIVESTATUS_VIRTUAL_FAILURE';

export const DELETE_VIRTUALCARD_SUCCESS = 'DELETE_VIRTUALCARD_SUCCESS';
export const DELETE_VIRTUALCARD_PENDING = 'DELETE_VIRTUALCARD_PENDING';
export const DELETE_VIRTUALCARD_FAILURE = 'DELETE_VIRTUALCARD_FAILURE';

export const GET_VIRTUALCARD_HISTORY_SUCCESS = 'GET_VIRTUALCARD_HISTORY_SUCCESS';
export const GET_VIRTUALCARD_HISTORY_PENDING = 'GET_VIRTUALCARD_HISTORY_PENDING';
export const GET_VIRTUALCARD_HISTORY_FAILURE = 'GET_VIRTUALCARD_HISTORY_FAILURE';

//ALAT ATM CARD CONSTANTS

export const GETCURRENT_ATMCARD_SUCCESS = 'GETCURRENT_ATMCARD_SUCCESS';
export const GETCURRENT_ATMCARD_PENDING = 'GETCURRENT_ATMCARD_PENDING';
export const GETCURRENT_ATMCARD_FAILURE = 'GETCURRENT_ATMCARD_FAILURE';

export const GET_ATMCARD_HOTLISTREASONS_SUCCESS = 'GET_ATMCARD_HOTLISTREASONS_SUCCESS';
export const GET_ATMCARD_HOTLISTREASONS_PENDING = 'GET_ATMCARD_HOTLISTREASONS_PENDING';
export const GET_ATMCARD_HOTLISTREASONS_FAILURE = 'GET_ATMCARD_HOTLISTREASONS_FAILURE';

export const HOTLIST_ATMCARD_SUCCESS = 'HOTLIST_ATMCARD_SUCCESS';
export const HOTLIST_ATMCARD_PENDING = 'HOTLIST_ATMCARD_PENDING';
export const HOTLIST_ATMCARD_FAILURE = 'HOTLIST_ATMCARD_FAILURE';

export const GETRANDOM_SECURITYQUESTION_SUCCESS = 'GETRANDOM_SECURITYQUESTION_SUCCESS';
export const GETRANDOM_SECURITYQUESTION_PENDING = 'GETRANDOM_SECURITYQUESTION_PENDING';
export const GETRANDOM_SECURITYQUESTION_FAILURE = 'GETRANDOM_SECURITYQUESTION_FAILURE';

export const VALIDATE_SECURITYQUESTION_WITHOUTOTP_SUCCESS = 'VALIDATE_SECURITYQUESTION_WITHOUTOTP_SUCCESS';
export const VALIDATE_SECURITYQUESTION_WITHOUTOTP_PENDING = 'VALIDATE_SECURITYQUESTION_WITHOUTOTP_PENDING';
export const VALIDATE_SECURITYQUESTION_WITHOUTOTP_FAILURE = 'VALIDATE_SECURITYQUESTION_WITHOUTOTP_FAILURE';

export const ACTIVATE_ALATCARD_SUCCESS = 'ACTIVATE_ALATCARD_SUCCESS';
export const ACTIVATE_ALATCARD_PENDING = 'ACTIVATE_ALATCARD_PENDING';
export const ACTIVATE_ALATCARD_FAILURE = 'ACTIVATE_ALATCARD_FAILURE';

export const GETALAT_CARDSETTINGS_SUCCESS = 'GETALAT_CARDSETTINGS_SUCCESS';
export const GETALAT_CARDSETTINGS_PENDING = 'GETALAT_CARDSETTINGS_PENDING';
export const GETALAT_CARDSETTINGS_FAILURE = 'GETALAT_CARDSETTINGS_FAILURE';

export const UPDATEALAT_CARDSETTINGS_SUCCESS = 'UPDATEALAT_CARDSETTINGS_SUCCESS';
export const UPDATEALAT_CARDSETTINGS_PENDING = 'UPDATEALAT_CARDSETTINGS_PENDING';
export const UPDATEALAT_CARDSETTINGS_FAILURE = 'UPDATEALAT_CARDSETTINGS_FAILURE';



export const ALATCARD_REDUCER_CLEAR = 'ALATCARD_REDUCER_CLEAR';





