export const FETCH_CURRENTCARD_SUCCESS = 'FETCH_CURRENTCARD_SUCCESS';
export const FETCH_CURRENTCARD_PENDING = 'FETCH_CURRENTCARD_PENDING';
export const FETCH_CURRENTCARD_FAILURE = 'FETCH_CURRENTCARD_FAILURE';

export const SEND_NEWVC_DATA_SUCCESS = 'SEND_NEWVC_DATA_SUCCESS';
export const SEND_NEWVC_DATA_PENDING = 'SEND_NEWVC_DATA_PENDING';
export const SEND_NEWVC_DATA_FAILURE = 'SEND_NEWVC_DATA_FAILURE';


export const FETCH_CARD_DATA_SUCCESS = 'FETCH_CARD_DATA_SUCCESS';
export const FETCH_CARD_DATA_PENDING = 'FETCH_CARD_DATA_PENDING';
export const FETCH_CARD_DATA_FAILURE = 'FETCH_CARD_DATA_FAILURE';


export const SEND_TOPUP_DATA_SUCCESS = 'SEND_TOPUP_DATA_SUCCESS';
export const SEND_TOPUP_DATA_PENDING = 'SEND_TOPUP_DATA_PENDING';
export const SEND_TOPUP_DATA_FAILURE = 'SEND_TOPUP_DATA_FAILURE';

export const LIQUIDATE_CARD_SUCCESS = 'LIQUIDATE_CARD_SUCCESS';
export const LIQUIDATE_CARD_PENDING = 'LIQUIDATE_CARD_PENDING';
export const LIQUIDATE_CARD_FAILURE = 'LIQUIDATE_CARD_FAILURE';

export const DELETE_VIRTUALCARD_SUCCESS = 'DELETE_VIRTUALCARD_SUCCESS';
export const DELETE_VIRTUALCARD_PENDING = 'DELETE_VIRTUALCARD_PENDING';
export const DELETE_VIRTUALCARD_FAILURE = 'DELETE_VIRTUALCARD_FAILURE';

export const GET_VIRTUALCARD_HISTORY_SUCCESS = 'GET_VIRTUALCARD_HISTORY_SUCCESS';
export const GET_VIRTUALCARD_HISTORY_PENDING = 'GET_VIRTUALCARD_HISTORY_PENDING';
export const GET_VIRTUALCARD_HISTORY_FAILURE = 'GET_VIRTUALCARD_HISTORY_FAILURE';

export const ALATCARD_REDUCER_CLEAR = 'ALATCARD_REDUCER_CLEAR';





