export const FETCH_CURRENTCARD_SUCCESS = 'FETCH_CURRENTCARD_SUCCESS';
export const FETCH_CURRENTCARD_PENDING = 'FETCH_CURRENTCARD_PENDING';
export const FETCH_CURRENTCARD_FAILURE = 'FETCH_CURRENTCARD_FAILURE';

export const ALATCARD_REDUCER_CLEAR = 'ALATCARD_REDUCER_CLEAR';





