export const airtimeConstants = {
    AIRTIME_BENEFICIARIES_FETCH_SUCCESS : 'AIRTIME_BENEFICIARIES_FETCH_SUCCESS',
    AIRTIME_BENEFICIARIES_FETCH_PENDING : 'AIRTIME_BENEFICIARIES_FETCH_PENDING',
    AIRTIME_BENEFICIARIES_FETCH_FAILURE : 'AIRTIME_BENEFICIARIES_FETCH_FAILURE',

    AIRTIME_BENEFICIARIES_DELETE_SUCCESS : 'AIRTIME_BENEFICIARIES_DELETE_SUCCESS',
    AIRTIME_BENEFICIARIES_DELETE_PENDING : 'AIRTIME_BENEFICIARIES_DELETE_PENDING',
    AIRTIME_BENEFICIARIES_DELETE_FAILURE : 'AIRTIME_BENEFICIARIES_DELETE_FAILURE',

    GET_DEBTABLE_ACCOUNTS_PENDING: 'GET_DEBTABLE_ACCOUNTS_PENDING',
    GET_DEBTABLE_ACCOUNTS_SUCCESS: 'GET_DEBTABLE_ACCOUNTS_SUCCESS',
    GET_DEBTABLE_ACCOUNTS_FAILURE: 'GET_DEBTABLE_ACCOUNTS_FAILURE',

    AIRTIME_BUYDATA_PAGE1: 'AIRTIME_BUYDATA_PAGE1',
    AIRTIME_BUYDATA_PAGE2: 'AIRTIME_BUYDATA_PAGE2',
    AIRTIME_BUYDATA_PAGE3: 'AIRTIME_BUYDATA_PAGE3'
};