export const airtimeConstants = {
    AIRTIME_BENEFICIARIES_FETCH_SUCCESS : 'AIRTIME_BENEFICIARIES_FETCH_SUCCESS',
    AIRTIME_BENEFICIARIES_FETCH_PENDING : 'AIRTIME_BENEFICIARIES_FETCH_PENDING',
    AIRTIME_BENEFICIARIES_FETCH_FAILURE : 'AIRTIME_BENEFICIARIES_FETCH_FAILURE'
};