export const FETCH_BILLS_BENEFICIARY_SUCCESS = 'FETCH_BILLS_BENEFICIARY_SUCCESS';
export const FETCH_BILLER_ITEMS_SUCCESS = 'FETCH_BILLER_ITEMS_SUCCESS';


export const IS_FETCHING_TRUE = 'IS_FETCHING_TRUE';
export const IS_FETCHING_FALSE = 'IS_FETCHING_FALSE';
export const IS_FETCHING_BILLER_ITEM = 'IS_FETCHING_BILLER_ITEM';

export const FETCH_BILLERS_CATEGORY_SUCCESS = 'FETCH_BILLERS_CATEGORY_SUCCESS';

export const RESET_PAGE_STATE_BILL = 'RESET_PAGE_STATE_BILL';
export const SUCCESS_NEXT_PAGE_BILL = 'SUCCESS_NEXT_PAGE_BILL';
export const COMPLETE_TO_DASHBOARD_BILL = 'COMPLETE_TO_DASHBOARD_BILL';
export const CLEAR_BILLS_DATA = 'CLEAR_BILLS_DATA';


export const SET_BILL_TO_PAY_INFO = 'SET_BILL_TO_PAY_INFO';