export const IS_FETCHING_TRUE  = 'IS_FETCHING_TRUE';
export const IS_FETCHING_FALSE = 'IS_FETCHING_FALSE';
export const IS_FETCHING_HISTORY = 'IS_FETCHING_HISTORY';

export const CLEAR_CURRENT_HISTORY = 'CLEAR_CURRENT_HISTORY';
export const SET_RECEIVED_TRANSACTIONS = 'SET_RECEIVED_TRANSACTIONS';

export const IS_SENDING_RECEIPT = 'IS_SENDING_RECEIPT';
export const SEND_RECEIPT_SUCCESS = 'SEND_RECEIPT_SUCCESS';
export const CLEAR_RESPONSE = 'CLEAR_RESPONSE';


export const FETCHING_HISTORY_SUCCESS = 'FETCHING_HISTORY_SUCCESS';
export const FETCHING_RECEIPT_HISTORY_SUCCESS = 'FETCHING_RECEIPT_HISTORY_SUCCESS';

export const SEND_STATEMENT_START = 'SEND_STATEMENT_START';
export const SEND_STATEMENT_SUCCESS = 'SEND_STATEMENT_SUCCESS';

export const GET_LIMIT_SUCCESS = 'GET_LIMIT_SUCCESS';
export const GET_LIMIT_FAILED = 'GET_LIMIT_FAILED';

export const SET_LIMIT_DATA = 'SET_LIMIT_DATA';
export const SUCCESS_NEXT_PAGE = 'SUCCESS_NEXT_PAGE';

export const RESET_PAGE_STATE = 'RESET_PAGE_STATE';