export const fundAccountConstants = {
    FUND_ALAT_WEMA_SUCCESS : "FUND_ALAT_WEMA_SUCCESS",
    FUND_ALAT_WEMA_PENDING: "FUND_ALAT_WEMA_PENDING",
    FUND_ALAT_WEMA_FAILURE : "FUND_ALAT_WEMA_FAILURE",

    GET_TOKENIZED_CARDS_SUCCESS : "GET_TOKENIZED_CARDS_SUCCESS",
    GET_TOKENIZED_CARDS_PENDING : "GET_TOKENIZED_CARDS_PENDING",
    GET_TOKENIZED_CARDS_FAILURE : "GET_TOKENIZED_CARDS_FAILURE",

    SAVE_CARD_SUCCESS :"SAVE_CARD_SUCCESS",
    SAVE_CARD_PENDING :"SAVE_CARD_PENDING",
    SAVE_CARD_FAILURE :"SAVE_CARD_FAILURE",
    SAVE_CARD_CLEAR : "SAVE_CARD_CLEAR",

    FUNDCARD_DETAILS_SUCCESS: "FUNDCARD_DETAILS_SUCCESS",
    FUNDCARD_DETAILS_PENDING: "FUNDCARD_DETAILS_PENDING",
    FUNDCARD_DETAILS_FAILURE: "FUNDCARD_DETAILS_FAILURE",
    FUNDCARD_DETAILS_CLEAR: "FUNDCARD_DETAILS_CLEAR",

    FUNDACCOUNT_CARD_SUCCESS: "FUNDACCOUNT_CARD_SUCCESS",
    FUNDACCOUNT_CARD_PENDING: "FUNDACCOUNT_CARD_PENDING",
    FUNDACCOUNT_CARD_FAILURE: "FUNDACCOUNT_CARD_FAILURE",

    DELETE_SAVED_CARD_SUCCESS: "DELETE_SAVED_CARD_SUCCESS",
    DELETE_SAVED_CARD_PENDING: "DELETE_SAVED_CARD_PENDING",
    DELETE_SAVED_CARD_FAILURE: "DELETE_SAVED_CARD_FAILURE",
    DELETE_SAVED_CARD_CLEAR: "DELETE_SAVED_CARD_CLEAR",

    FUND_FROM_CARD_SUCCESS: "FUND_FROM_CARD_SUCCESS",
    FUND_FROM_CARD_PENDING: "FUND_FROM_CARD_PENDING",
    FUND_FROM_CARD_FAILURE: "FUND_FROM_CARD_FAILURE",
};