export const fundAccountConstants = {
    FUND_ALAT_WEMA_SUCCESS : "FUND_ALAT_WEMA_SUCCESS",
    FUND_ALAT_WEMA_PENDING: "FUND_ALAT_WEMA_PENDING",
    FUND_ALAT_WEMA_FAILURE : "FUND_ALAT_WEMA_FAILURE",

    GET_TOKENIZED_CARDS_SUCCESS : "GET_TOKENIZED_CARDS_SUCCESS",
    GET_TOKENIZED_CARDS_PENDING : "GET_TOKENIZED_CARDS_PENDING",
    GET_TOKENIZED_CARDS_FAILURE : "GET_TOKENIZED_CARDS_FAILURE",

    SAVE_CARD_SUCCESS :"SAVE_CARD_SUCCESS",
    SAVE_CARD_PENDING :"SAVE_CARD_PENDING",
    SAVE_CARD_FAILURE :"SAVE_CARD_FAILURE",
    SAVE_CARD_CLEAR : "SAVE_CARD_CLEAR",

    FUNDCARD_DETAILS_SUCCESS: "FUNDCARD_DETAILS_SUCCESS",
    FUNDCARD_DETAILS_PENDING: "FUNDCARD_DETAILS_PENDING",
    FUNDCARD_DETAILS_FAILURE: "FUNDCARD_DETAILS_FAILURE",
    FUNDCARD_DETAILS_CLEAR: "FUNDCARD_DETAILS_CLEAR",

    FUNDACCOUNT_CARD_SUCCESS: "FUNDACCOUNT_CARD_SUCCESS",
    FUNDACCOUNT_CARD_PENDING: "FUNDACCOUNT_CARD_PENDING",
    FUNDACCOUNT_CARD_FAILURE: "FUNDACCOUNT_CARD_FAILURE",

    DELETE_SAVED_CARD_SUCCESS: "DELETE_SAVED_CARD_SUCCESS",
    DELETE_SAVED_CARD_PENDING: "DELETE_SAVED_CARD_PENDING",
    DELETE_SAVED_CARD_FAILURE: "DELETE_SAVED_CARD_FAILURE",
    DELETE_SAVED_CARD_CLEAR: "DELETE_SAVED_CARD_CLEAR",

    FUND_FROM_CARD_SUCCESS: "FUND_FROM_CARD_SUCCESS",
    FUND_FROM_CARD_PENDING: "FUND_FROM_CARD_PENDING",
    FUND_FROM_CARD_FAILURE: "FUND_FROM_CARD_FAILURE",

    FUNDFROM_CARDWITH_PIN_SUCCESS: "FUNDFROM_CARDWITH_PIN_SUCCESS",
    FUNDFROM_CARDWITH_PIN_PENDING: "FUNDFROM_CARDWITH_PIN_PENDING",
    FUNDFROM_CARDWITH_PIN_FAILURE: "FUNDFROM_CARDWITH_PIN_FAILURE",


    ENCRYPTION_RULE_SUCCESS: "ENCRYPTION_RULE_SUCCESS",
    ENCRYPTION_RULE_PENDING: "ENCRYPTION_RULE_PENDING",
    ENCRYPTION_RULE_FAILURE: "ENCRYPTION_RULE_FAILURE",
    ENCRYPTION_RULE_CLEAR: "ENCRYPTION_RULE_CLEAR",

    VERIFY_PAN_SUCCESS: "VERIFY_PAN_SUCCESS",
    VERIFY_PAN_PENDING: "VERIFY_PAN_PENDING",
    VERIFY_PAN_FAILURE: "VERIFY_PAN_FAILURE",
    VERIFY_PAN_CLEAR: "VERIFY_PAN_CLEAR",

    FUND_ACCOUNT_SUCCESS : "FUND_ACCOUNT_SUCCESS",
    FUND_ACCOUNT_PENDING : "FUND_ACCOUNT_PENDING",
    FUND_ACCOUNT_FAILURE : "FUND_ACCOUNT_FAILURE",

    SAVEAFTER_TRANSACTION_SUCCESS: "SAVEAFTER_TRANSACTION_SUCCESS",
    SAVEAFTER_TRANSACTION_PENDING : "SAVEAFTER_TRANSACTION_PENDING",
    SAVEAFTER_TRANSACTION_FAILURE : "SAVEAFTER_TRANSACTION_FAILURE",

    FUND_ACCOUNT_REDUCER_CLEAR: "FUND_ACCOUNT_REDUCER_CLEAR"
};
