export const fundAccountConstants = {
    FUND_ALAT_WEMA_SUCCESS : "FUND_ALAT_WEMA_SUCCESS",
    FUND_ALAT_WEMA_PENDING: "FUND_ALAT_WEMA_PENDING",
    FUND_ALAT_WEMA_FAILURE : "FUND_ALAT_WEMA_FAILURE",

    GET_TOKENIZED_CARDS_SUCCESS : "GET_TOKENIZED_CARDS_SUCCESS",
    GET_TOKENIZED_CARDS_PENDING : "GET_TOKENIZED_CARDS_PENDING",
    GET_TOKENIZED_CARDS_FAILURE : "GET_TOKENIZED_CARDS_FAILURE"
};