export const listStyleConstants = {
    GET_CINEMA_LIST_PENDING: "GET_CINEMA_LIST_PENDING",
    GET_CINEMA_LIST_SUCCESS: "GET_CINEMA_LIST_SUCCESS",
    GET_CINEMA_LIST_ERROR: "GET_CINEMA_LIST_ERROR"
}