export const listStyleConstants = {
    //GET CINEMA LIST
    GET_CINEMA_LIST_PENDING: "GET_CINEMA_LIST_PENDING",
    GET_CINEMA_LIST_SUCCESS: "GET_CINEMA_LIST_SUCCESS",
    GET_CINEMA_LIST_ERROR: "GET_CINEMA_LIST_ERROR",


    GET_SINGLE_MOVIE_PENDING: "GET_SINGLE_MOVIE_PENDING",
    GET_SINGLE_MOVIE_SUCCESS: "GET_SINGLE_MOVIE_SUCCESS",
    GET_SINGLE_MOVIE_ERROR: "GET_SINGLE_MOVIE_ERROR",


    BUY_MOVIE_TICKET_PENDING: "BUY_MOVIE_TICKET_PENDING",
    BUY_MOVIE_TICKET_SUCCESS: "BUY_MOVIE_TICKET_SUCCESS",
    BUY_MOVIE_TICKET_ERROR: "BUY_MOVIE_TICKET_ERROR",

    //GET EVENTS
    GET_EVENTS_PENDING: 'GET_EVENTS_PENDING',
    GET_EVENTS_SUCCESS: "GET_EVENTS_SUCCESS",
    GET_EVENTS_ERROR: "GET_EVENTS_ERROR",

    GET_SINGLE_EVENT_PENDING: "GET_SINGLE_EVENT_PENDING",
    GET_SINGLE_EVENT_SUCCESS: "GET_SINGLE_EVENT_SUCCESS",
    GET_SINGLE_EVENT_ERROR: "GET_SINGLE_EVENT_ERROR",

    BUY_EVENT_TICKET_PENDING: "BUY_EVENT_TICKET_PENDING",
    BUY_EVENT_TICKET_SUCCESS: "BUY_EVENT_TICKET_SUCCESS",
    BUY_EVENT_TICKET_ERROR: "BUY_EVENT_TICKET_ERROR",

    PREFERENCES_PENDING: "PREFERENCES_PENDING",
    PREFERENCES_SUCCESS: "PREFERENCES_SUCCESS",
    PREFERENCES_ERROR: "PREFERENCES_ERROR",

    GET_MOVIE_LIST_PENDING:"GET_MOVIE_LIST_PENDING",
    GET_MOVIE_LIST_SUCCESS:"GET_MOVIE_LIST_SUCCESS",
    GET_MOVIE_LIST_FAILURE:"GET_MOVIE_LIST_FAILURE",

    GET_CUSTOMER_ENGAGEMENT_PENDING: "GET_CUSTOMER_ENGAGEMENT_PENDING",
    GET_CUSTOMER_ENGAGEMENT_SUCCESS: "GET_CUSTOMER_ENGAGEMENT_SUCCESS",
    GET_CUSTOMER_ENGAGEMENT_FAILURE: "GET_CUSTOMER_ENGAGEMENT_FAILURE",

    GET_MOVIE_SHOWTIME_PENDING: "GET_MOVIE_SHOWTIME_PENDING",
    GET_MOVIE_SHOWTIME_SUCCESS: "GET_MOVIE_SHOWTIME_SUCCESS",
    GET_MOVIE_SHOWTIME_FAILURE: "GET_MOVIE_SHOWTIME_FAILURE",

    SUBMIT_MOVIE_TICKET_PENDING: "SUBMIT_MOVIE_TICKET_PENDING",
    SUBMIT_MOVIE_TICKET_SUCCESS: "SUBMIT_MOVIE_TICKET_SUCCESS",
    SUBMIT_MOVIE_TICKET_FAILURE: "SUBMIT_MOVIE_TICKET_FAILURE",


}




















