export const loanOnboardingConstants = { 
    LOAN_STEP1_PENDING: 'LOAN_STEP1_PENDING',
    LOAN_STEP1_SUCCESS: 'LOAN_STEP1_SUCCESS',
    LOAN_STEP1_FAILURE: 'LOAN_STEP1_FAILURE',

    LOAN_STEP2_PENDING: 'LOAN_STEP2_PENDING',
    LOAN_STEP2_SUCCESS: 'LOAN_STEP2_SUCCESS',
    LOAN_STEP2_FAILURE: 'LOAN_STEP2_FAILURE',

    LOAN_STEP3_PENDING: 'LOAN_STEP3_PENDING',
    LOAN_STEP3_SUCCESS: 'LOAN_STEP3_SUCCESS',
    LOAN_STEP3_FAILURE: 'LOAN_STEP3_FAILURE',

    LOAN_VERIFY_BVN_SUCCESS : 'LOAN_VERIFY_BVN_SUCCESS',
    LOAN_VERIFY_BVN_PENDING : 'LOAN_VERIFY_BVN_PENDING',
    LOAN_VERIFY_BVN_FAILURE : 'LOAN_VERIFY_BVN_FAILURE',

    LOAN_VALIDATEOTP_SUCCESS : 'LOAN_VALIDATEOTP_SUCCESS',
    LOAN_VALIDATEOTP_PENDING : 'LOAN_VALIDATEOTP_PENDING',
    LOAN_VALIDATEOTP_FAILURE : 'LOAN_VALIDATEOTP_FAILURE',

    LOAN_GENERATE_STATEMENT_SUCCESS : 'LOAN_GENERATE_STATEMENT_SUCCESS',
    LOAN_GENERATE_STATEMENT_PENDING : 'LOAN_GENERATE_STATEMENT_PENDING',
    LOAN_GENERATE_STATEMENT_FAILURE : 'LOAN_GENERATE_STATEMENT_FAILURE',

    LOAN_REQUEST_STATEMENT_SUCCESS : 'LOAN_REQUEST_STATEMENT_SUCCESS',
    LOAN_REQUEST_STATEMENT_PENDING : 'LOAN_REQUEST_STATEMENT_PENDING',
    LOAN_REQUEST_STATEMENT_FAILURE : 'LOAN_REQUEST_STATEMENT_FAILURE',

    LOAN_SALARYENTRY_SUCCESS : 'LOAN_SALARYENTRY_SUCCESS',
    LOAN_SALARYENTRY_PENDING : 'LOAN_SALARYENTRY_PENDING',
    LOAN_SALARYENTRY_FAILURE : 'LOAN_SALARYENTRY_FAILURE',


    LOAN_ONBOARDING_REDUCER_CLEAR: 'LOAN_ONBOARDING_REDUCER_CLEAR',
}