export const loanOnboardingConstants = { 
    LOAN_STEP1_PENDING: 'LOAN_STEP1_PENDING',
    LOAN_STEP1_SUCCESS: 'LOAN_STEP1_SUCCESS',
    LOAN_STEP1_FAILURE: 'LOAN_STEP1_FAILURE',

    LOAN_ONBOARDING_REDUCER_CLEAR: 'LOAN_ONBOARDING_REDUCER_CLEAR',
}