export const dashboardConstants = {

    DASHBOARD_ACCOUNT_FETCH_SUCCESS: 'DASHBOARD_ACCOUNT_FETCH_SUCCESS',
    DASHBOARD_ACCOUNT_FETCH_PENDING: 'DASHBOARD_ACCOUNT_FETCH_PENDING',
    DASHBOARD_ACCOUNT_FETCH_FAILURE: 'DASHBOARD_ACCOUNT_FETCH_FAILURE',

    DASHBOARD_ACCOUNT_FETCH_HISTORY_SUCCESS: 'DASHBOARD_ACCOUNT_FETCH_HISTORY_SUCCESS',
    DASHBOARD_ACCOUNT_FETCH_HISTORY_PENDING: 'DASHBOARD_ACCOUNT_FETCH_HISTORY_PENDING',
    DASHBOARD_ACCOUNT_FETCH_HISTORY_FAILURE: 'DASHBOARD_ACCOUNT_FETCH_HISTORY_FAILURE',

    DASHBOARD_GOALS_SUMMARY_FETCH_SUCCESS: 'DASHBOARD_GOALS_SUMMARY_FETCH_SUCCESS',
    DASHBOARD_GOALS_SUMMARY_FETCH_PENDING: 'DASHBOARD_GOALS_SUMMARY_FETCH_PENDING',
    DASHBOARD_GOALS_SUMMARY_FETCH_FAILURE: 'DASHBOARD_GOALS_SUMMARY_FETCH_FAILURE',

    DASHBOARD_ONBOARDING_PRIORITY_SUCCESS: 'DASHBOARD_ONBOARDING_PRIORITY_SUCCESS',
    DASHBOARD_ONBOARDING_PRIORITY_PENDING: 'DASHBOARD_ONBOARDING_PRIORITY_PENDING',

    ANNOUNCEMENT_FETCH_PENDING: 'ANNOUNCEMENT_FETCH_PENDING',
    ANNOUNCEMENT_FETCH_SUCCESS: 'ANNOUNCEMENT_FETCH_SUCCESS',
};
