export const FETCH_ALL_UNEXPIRED_PAYCODES = 'FETCH_ALL_UNEXPIRED_PAYCODES';
export const FETCH_ALL_UNEXPIRED_PAYCODES_SUCCESS = 'FETCH_ALL_UNEXPIRED_PAYCODES_SUCCESS';

export const SET_CARDLESS_WITHDRAWAL_INFO = 'SET_CARDLESS_WITHDRAWAL_INFO';

export const RESET_PAGE_STATE = 'RESET_PAGE_STATE';
export const SUCCESS_NEXT_PAGE = 'SUCCESS_NEXT_PAGE';
export const COMPLETE_TO_DASHBOARD = 'COMPLETE_TO_DASHBOARD';
export const CLEAR_CARDLESS_DATA = 'CLEAR_CARDLESS_DATA';


export const IS_FETCHING_TRUE = 'IS_FETCHING_TRUE';
export const IS_FETCHING_FALSE = 'IS_FETCHING_FALSE';