export const FETCH_ALL_UNEXPIRED_PAYCODES = 'FETCH_ALL_UNEXPIRED_PAYCODES';
export const FETCH_ALL_UNEXPIRED_PAYCODES_SUCCESS = 'FETCH_ALL_UNEXPIRED_PAYCODES_SUCCESS';

export const SET_CARDLESS_WITHDRAWAL_INFO = 'SET_CARDLESS_WITHDRAWAL_INFO';


export const IS_FETCHING_TRUE = 'IS_FETCHING_TRUE';
export const IS_FETCHING_FALSE = 'IS_FETCHING_FALSE';