//
// In App Loan Specific Constants
//

export const loanConstants = { 


    // LOAN_STEP2_PENDING: 'LOAN_STEP2_PENDING',
    // LOAN_STEP2_SUCCESS: 'LOAN_STEP2_SUCCESS',
    // LOAN_STEP2_FAILURE: 'LOAN_STEP2_FAILURE',

    // LOAN_STEP3_PENDING: 'LOAN_STEP3_PENDING',
    // LOAN_STEP3_SUCCESS: 'LOAN_STEP3_SUCCESS',
    // LOAN_STEP3_FAILURE: 'LOAN_STEP3_FAILURE',
    LOAN_KYCREQUIRED_PENDING: 'LOAN_KYCREQUIRED_PENDING',
    LOAN_KYCREQUIRED_SUCCESS: 'LOAN_KYCREQUIRED_SUCCESS',
    LOAN_KYCREQUIRED_FAILURE: 'LOAN_KYCREQUIRED_FAILURE',

    LOAN_CONTINUE_APPLICATION : 'LOAN_CONTINUE_APPLICATION',

    LOAN_STATEMENT_UPLOAD_PENDING: 'LOAN_STATEMENT_UPLOAD_PENDING',
    LOAN_STATEMENT_UPLOAD_SUCCESS: 'LOAN_STATEMENT_UPLOAD_SUCCESS',
    LOAN_STATEMENT_UPLOAD_FAILURE: 'LOAN_STATEMENT_UPLOAD_FAILURE',


    LOAN_MANDATE_STATUS_PENDING: 'LOAN_MANDATE_STATUS_PENDING',
    LOAN_MANDATE_STATUS_SUCCESS: 'LOAN_MANDATE_STATUS_SUCCESS',
    LOAN_MANDATE_STATUS_FAILURE: 'LOAN_MANDATE_STATUS_FAILURE',

    LOAN_STAND_ORDER_PENDING: 'LOAN_STAND_ORDER_PENDING',
    LOAN_STAND_ORDER_SUCCESS: 'LOAN_STAND_ORDER_SUCCESS',
    LOAN_STAND_ORDER_FAILURE: 'LOAN_STAND_ORDER_FAILURE',
    
    LOAN_REJECT_PENDING: 'LOAN_REJECT_PENDING',
    LOAN_REJECT_SUCCESS: 'LOAN_REJECT_SUCCESS',
    LOAN_REJECT_FAILURE: 'LOAN_REJECT_FAILURE',

    LOAN_WORkID_FRONT_SUCCESS: 'LOAN_WORkID_FRONT_SUCCESS',
    LOAN_WORkID_FRONT_PENDING: 'LOAN_WORkID_FRONT_PENDING',
    LOAN_WORkID_FRONT_FAILURE: 'LOAN_WORkID_FRONT_FAILURE',

    LOAN_WORkID_BACK_SUCCESS: 'LOAN_WORkID_BACK_SUCCESS',
    LOAN_WORkID_BACK_PENDING: 'LOAN_WORkID_BACK_PENDING',
    LOAN_WORkID_BACK_FAILURE: 'LOAN_WORkID_BACK_FAILURE',

    LOAN_CURRENT_SUCCESS: 'LOAN_CURRENT_SUCCESS',
    LOAN_CURRENT_PENDING: 'LOAN_CURRENT_PENDING',
    LOAN_CURRENT_FAILURE: 'LOAN_CURRENT_FAILURE',

    LOAN_HISTORY_SUCCESS: 'LOAN_HISTORY_SUCCESS',
    LOAN_HISTORY_PENDING: 'LOAN_HISTORY_PENDING',
    LOAN_HISTORY_FAILURE: 'LOAN_HISTORY_FAILURE',

    LOAN_CALC_DATA_SUCCESS: 'LOAN_CALC_DATA_SUCCESS',
    LOAN_CALC_DATA_PENDING: 'LOAN_CALC_DATA_PENDING',
    LOAN_CALC_DATA_FAILURE: 'LOAN_CALC_DATA_FAILURE',

    LOAN_APPLY_SUCCESS: 'LOAN_APPLY_SUCCESS',
    LOAN_APPLY_PENDING: 'LOAN_APPLY_PENDING',
    LOAN_APPLY_FAILURE : 'LOAN_APPLY_FAILURE',

    LOAN_EMPLOYER_SUCCESS: 'LOAN_EMPLOYER_SUCCESS',
    LOAN_EMPLOYER_PENDING: 'LOAN_EMPLOYER_PENDING',
    LOAN_EMPLOYER_FAILURE: 'LOAN_EMPLOYER_FAILURE',
     
    LOAN_GETINDUSTRIES_SUCCESS : "LOAN_GETINDUSTRIES_SUCCESS",
    LOAN_GETINDUSTRIES_PENDING : "LOAN_GETINDUSTRIES_PENDING",
    LOAN_GETINDUSTRIES_FAILURE : "LOAN_GETINDUSTRIES_FAILURE",

    LOAN_VALIDATEOTP_SUCCESS : 'LOAN_VALIDATEOTP_SUCCESS',
    LOAN_VALIDATEOTP_PENDING : 'LOAN_VALIDATEOTP_PENDING',
    LOAN_VALIDATEOTP_FAILURE : 'LOAN_VALIDATEOTP_FAILURE',

    LOAN_GENERATE_STATEMENT_SUCCESS : 'LOAN_GENERATE_STATEMENT_SUCCESS',
    LOAN_GENERATE_STATEMENT_PENDING : 'LOAN_GENERATE_STATEMENT_PENDING',
    LOAN_GENERATE_STATEMENT_FAILURE : 'LOAN_GENERATE_STATEMENT_FAILURE',

    LOAN_REQUEST_STATEMENT_SUCCESS : 'LOAN_REQUEST_STATEMENT_SUCCESS',
    LOAN_REQUEST_STATEMENT_PENDING : 'LOAN_REQUEST_STATEMENT_PENDING',
    LOAN_REQUEST_STATEMENT_FAILURE : 'LOAN_REQUEST_STATEMENT_FAILURE',

    LOAN_SALARYTRANSACTION_SUCCESS : 'LOAN_SALARYTRANSACTION_SUCCESS',
    LOAN_SALARYTRANSACTION_PENDING : 'LOAN_SALARYTRANSACTION_PENDING',
    LOAN_SALARYTRANSACTION_FAILURE : 'LOAN_SALARYTRANSACTION_FAILURE',

    LOAN_SALARYENTRY_SUCCESS : 'LOAN_SALARYENTRY_SUCCESS',
    LOAN_SALARYENTRY_PENDING : 'LOAN_SALARYENTRY_PENDING',
    LOAN_SALARYENTRY_FAILURE : 'LOAN_SALARYENTRY_FAILURE',

    LOAN_SCORECARD_QUESTION_SUCCESS: 'LOAN_SCORECARD_QUESTION_SUCCESS',
    LOAN_SCORECARD_QUESTION_PENDING: 'LOAN_SCORECARD_QUESTION_PENDING',
    LOAN_SCORECARD_QUESTION_FAILURE: 'LOAN_SCORECARD_QUESTION_FAILURE',

    LOAN_SCORECARD_ANSWER_SUCCESS: 'LOAN_SCORECARD_ANSWER_SUCCESS',
    LOAN_SCORECARD_ANSWER_PENDING: 'LOAN_SCORECARD_ANSWER_PENDING',
    LOAN_SCORECARD_ANSWER_FAILURE: 'LOAN_SCORECARD_ANSWER_FAILURE',

    LOAN_USERNAME_SUCCESS: 'LOAN_USERNAME_SUCCESS',


    LOAN_ONBOARDING_CLEAR: 'LOAN_ONBOARDING_CLEAR',
}