//
// In App Loan Specific Constants
//

export const loanConstants = { 


    // LOAN_STEP2_PENDING: 'LOAN_STEP2_PENDING',
    // LOAN_STEP2_SUCCESS: 'LOAN_STEP2_SUCCESS',
    // LOAN_STEP2_FAILURE: 'LOAN_STEP2_FAILURE',

    // LOAN_STEP3_PENDING: 'LOAN_STEP3_PENDING',
    // LOAN_STEP3_SUCCESS: 'LOAN_STEP3_SUCCESS',
    // LOAN_STEP3_FAILURE: 'LOAN_STEP3_FAILURE',
    LOAN_CALC_DATA_SUCCESS: 'LOAN_CALC_DATA_SUCCESS',
    LOAN_CALC_DATA_PENDING: 'LOAN_CALC_DATA_PENDING',
    LOAN_CALC_DATA_FAILURE: 'LOAN_CALC_DATA_FAILURE',

    LOAN_APPLY_SUCCESS: 'LOAN_APPLY_SUCCESS',
    LOAN_APPLY_PENDING: 'LOAN_APPLY_PENDING',
    LOAN_APPLY_FAILURE : 'LOAN_APPLY_FAILURE',

    LOAN_EMPLOYER_SUCCESS: 'LOAN_EMPLOYER_SUCCESS',
    LOAN_EMPLOYER_PENDING: 'LOAN_EMPLOYER_PENDING',
    LOAN_EMPLOYER_FAILURE: 'LOAN_EMPLOYER_FAILURE',
     
    LOAN_GETINDUSTRIES_SUCCESS : "LOAN_GETINDUSTRIES_SUCCESS",
    LOAN_GETINDUSTRIES_PENDING : "LOAN_GETINDUSTRIES_PENDING",
    LOAN_GETINDUSTRIES_FAILURE : "LOAN_GETINDUSTRIES_FAILURE",

    LOAN_VALIDATEOTP_SUCCESS : 'LOAN_VALIDATEOTP_SUCCESS',
    LOAN_VALIDATEOTP_PENDING : 'LOAN_VALIDATEOTP_PENDING',
    LOAN_VALIDATEOTP_FAILURE : 'LOAN_VALIDATEOTP_FAILURE',

    LOAN_GENERATE_STATEMENT_SUCCESS : 'LOAN_GENERATE_STATEMENT_SUCCESS',
    LOAN_GENERATE_STATEMENT_PENDING : 'LOAN_GENERATE_STATEMENT_PENDING',
    LOAN_GENERATE_STATEMENT_FAILURE : 'LOAN_GENERATE_STATEMENT_FAILURE',

    LOAN_REQUEST_STATEMENT_SUCCESS : 'LOAN_REQUEST_STATEMENT_SUCCESS',
    LOAN_REQUEST_STATEMENT_PENDING : 'LOAN_REQUEST_STATEMENT_PENDING',
    LOAN_REQUEST_STATEMENT_FAILURE : 'LOAN_REQUEST_STATEMENT_FAILURE',

    LOAN_SALARYTRANSACTION_SUCCESS : 'LOAN_SALARYTRANSACTION_SUCCESS',
    LOAN_SALARYTRANSACTION_PENDING : 'LOAN_SALARYTRANSACTION_PENDING',
    LOAN_SALARYTRANSACTION_FAILURE : 'LOAN_SALARYTRANSACTION_FAILURE',

    LOAN_SALARYENTRY_SUCCESS : 'LOAN_SALARYENTRY_SUCCESS',
    LOAN_SALARYENTRY_PENDING : 'LOAN_SALARYENTRY_PENDING',
    LOAN_SALARYENTRY_FAILURE : 'LOAN_SALARYENTRY_FAILURE',

    LOAN_SCORECARD_QUESTION_SUCCESS: 'LOAN_SCORECARD_QUESTION_SUCCESS',
    LOAN_SCORECARD_QUESTION_PENDING: 'LOAN_SCORECARD_QUESTION_PENDING',
    LOAN_SCORECARD_QUESTION_FAILURE: 'LOAN_SCORECARD_QUESTION_FAILURE',

    LOAN_SCORECARD_ANSWER_SUCCESS: 'LOAN_SCORECARD_ANSWER_SUCCESS',
    LOAN_SCORECARD_ANSWER_PENDING: 'LOAN_SCORECARD_ANSWER_PENDING',
    LOAN_SCORECARD_ANSWER_FAILURE: 'LOAN_SCORECARD_ANSWER_FAILURE',

    LOAN_USERNAME_SUCCESS: 'LOAN_USERNAME_SUCCESS',


    LOAN_ONBOARDING_CLEAR: 'LOAN_ONBOARDING_CLEAR',
}