// Group Savings Constants
//groupSavingsConstant
export const GROUPSAVINGSCONSTANT = {
    CREATEGROUPSAINGSPENDING: "CREATE_GROUP_SAVINGS_PENDING",
    CREATEGROUPSAVINGS_SUCCESS: "CREATE_GROUP_SAVINGS_SUCCESS",
    CREATEGROUPSAVINGS_ERROR: "CREATE_GROUP_SAVINGS_ERROR",

    GROUPDETAILS: "REQUESTING_GROUPDETAILS_PENDING",
    GROUPDETAILS_SUCCESS: "GROUPDETAILS_DETIALS_SUCCESS",
    GROUPDETAILS_ERROR: "GROUPDETAILS_DETIALS_ERROR",

    DELETEGROUP: "DELETTING GROUP_PENDING",
    DELETEGROUP_SUCCESS: "DELETEGROUP_SUCCESS",
    DELETEGROUP_ERROR: "DELETEGROUP_ERROR",

    CONTRIBUTE: "CONTRIBUTE_PENDING",
    CONTRIBUTE_SUCCESS: "CONTRIBUTE_SUCCESS",
    CONTRIBUTE_ERROR: "CONTRIBUTE_ERROR",

    EDITGROUP: "EDITGROUP_PENDING",
    EDITGROUP_SUCCESS: "EDITGROUP_SUCCESS",
    EDITGROUP_ERROR: "EDITGROUP_ERROR",

    PAUSEGROUP: "PAUSEGROUP_PENDING",
    PAUSEGROUP_SUCCESS: "PAUSEGROUP_SUCCESS",
    PAUSEGROUP_ERROR: "PAUSEGROUP_ERROR",

    FIND_GROUP: 'FIND_GROUP_PENDING',
    FIND_GROUP_SUCCESS: 'FIND_GROUP_SUCCESS',
    FIND_GROUP_ERROR: 'FIND_GROUP_ERROR',

    CUSTOMER_GROUP: 'CUSTOMER_GROUP_PENDING',
    CUSTOMER_GROUP_SUCCESS: 'CUSTOMER_GROUP_SUCCESS',
    CUSTOMER_GROUP_ERROR: 'CUSTOMER_GROUP_ERROR',

    JOIN_GROUP: 'JOIN_GROUP_PENDING',
    JOIN_GROUP_SUCCESS: 'JOIN_GROUP_SUCCESS',
    JOIN_GROUP_ERROR: 'JOIN_GROUP_ERROR',

    SCHEDULE_CONTRIBUTION: 'SCHEDULE_CONTRIBUTION_PENDING',
    SCHEDULE_CONTRIBUTION_SUCCESS: 'SCHEDULE_CONTRIBUTION_SUCCESS',
    SCHEDULE_CONTRIBUTION_ERROR: 'SCHEDULE_CONTRIBUTION_ERROR', 

    DELETE_MEMBER: 'DELETE_MEMBER_PENDING',
    DELETE_MEMBER_SUCCESS: 'DELETE_MEMBER_SUCCESS',
    DELETE_MEMBER_ERROR: 'DELETE_MEMBER_ERROR',

    CASHOUT: 'CASHOUT_PENDING',
    CASHOUT_SUCCESS: 'CASHOUT_SUCCESS',
    CASHOUT_ERROR: 'CASHOUT_ERROR',

    CONTINUE_SCHEDULEGROUP_PAYMENT: 'CONTINUE_SCHEDULEGROUP_PAYMENT_PENDING',
    CONTINUE_SCHEDULEGROUP_PAYMENT_SUCCESS: 'CONTINUE_SCHEDULEGROUP_PAYMENT_SUCCESS',
    CONTINUE_SCHEDULEGROUP_PAYMENT_ERROR: 'CONTINUE_SCHEDULEGROUP_PAYMENT_ERROR',

    GROUPSAVINGS_STARTDATE: 'GROUPSAVINGS_STARTDATE_PENDING',
    GROUPSAVINGS_ENDATE: 'GROUPSAVINGS_ENDATE',
    SETAMOUNT_TO_WITHDRAW: 'SETAMOUNT_TO_WITHDRAW',
    SET_FREQUENCY: 'SET_FREQUENCY',

    //ROTATING GROUP (ESUSU)

    ACTIVATE_ROTATING_GROUP_PENDING: 'ACTIVATE_ROTATING_GROUP_PENDING',
    ACTIVATE_ROTATING_GROUP_SUCCESS: 'ACTIVATE_ROTATING_GROUP_SUCCESS',
    ACTIVATE_ROTATING_GROUP_FAILURE: 'ACTIVATE_ROTATING_GROUP_FAILURE',

    CREATE_ROTATING_GROUP: 'CREATE_ROTATING_GROUP_PENDING',
    CREATE_ROTATING_GROUP_SUCCESS: 'CREATE_ROTATING_GROUP_SUCCESS',
    CREATE_ROTATING_GROUP_ERROR: 'CREATE_ROTATING_GROUP_ERROR',

    ROTATING_GROUP_DETAILS: 'ROTATING_GROUP_DETAILS_PENDING',
    ROTATING_GROUP_DETAILS_SUCCESS: 'ROTATING_GROUP_DETAILS_SUCCESS',
    ROTATING_GROUP_DETAILS_ERROR: 'ROTATING_GROUP_DETAILS_ERROR',
    JOIN_A_GROUP: 'JOIN_A_GROUP_PENDING',
    JOIN_A_GROUP_SUCCESS: 'JOIN_A_GROUP_SUCCESS',
    JOIN_A_GROUP_ERROR: 'JOIN_A_GROUP_ERROR',

    EDIT_SLOTS: 'EDIT_SLOTS_PENDING',
    EDIT_SLOTS_SUCCESS: 'EDIT_SLOTS_SUCCESS',
    EDIT_SLOTS_ERROR: 'EDIT_SLOTS_ERROR',

    GET_GROUPS_ESUSU: 'GET_GROUPS_PENDING',        
    GET_GROUPS_ESUSU_SUCCESS: 'GET_GROUPS_SUCCESS',
    GET_GROUPS_ESUSU_ERROR: 'GET_GROUPS_ERROR',

    EDIT_GROUP_ESUSU: 'EDIT_GROUP_ESUSU_PENDING',
    EDIT_GROUP_ESUSU_SUCCESS: 'EDIT_GROUP_ESUSU_SUCCESS',
    EDIT_GROUP_ESUSU_ERROR: 'EDIT_GROUP_ESUSU_ERROR',

    DELETE_GROUP_ESUSU: 'DELETE_GROUP_ESUSU_PENDING',
    DELETE_GROUP_ESUSU_SUCCESS: 'DELETE_GROUP_ESUSU_SUCCESS',
    DELETE_GROUP_ESUSU_ERROR: 'DELETE_GROUP_ESUSU_ERROR',
    
    JOIN_GROUP_ESUSU: 'JOIN_GROUP_ESUSU_PENDING',
    JOIN_GROUP_ESUSU_SUCCESS: 'JOIN_GROUP_ESUSU_SUCCESS',
    JOIN_GROUP_ESUSU_ERROR: 'JOIN_GROUP_ESUSU_ERROR'

}

 































