// Group Savings Constants
//groupSavingsConstant
export const GROUPSAVINGSCONSTANT = {
    CREATEGROUPSAINGSPENDING: "CREATE_GROUP_SAVINGS_PENDING",
    CREATEGROUPSAVINGS_SUCCESS: "CREATE_GROUP_SAVINGS_SUCCESS",
    CREATEGROUPSAVINGS_ERROR: "CREATE_GROUP_SAVINGS_ERROR",

    GROUPDETAILS: "REQUESTING_GROUPDETAILS",
    GROUPDETAILS_SUCCESS: "GROUPDETAILS_DETIALS_SUCCESS",
    GROUPDETAILS_ERROR: "GROUPDETAILS_DETIALS_ERROR",

    DELETEGROUP: "DELETTING GROUP",
    DELETEGROUP_SUCCESS: "DELETEGROUP_SUCCESS",
    DELETEGROUP_ERROR: "DELETEGROUP_ERROR",

    CONTRIBUTE: "CONTRIBUTE",
    CONTRIBUTE_SUCCESS: "CONTRIBUTE_SUCCESS",
    CONTRIBUTE_ERROR: "CONTRIBUTE_ERROR",

    EDITGROUP: "EDITGROUP",
    EDITGROUP_SUCCESS: "EDITGROUP_SUCCESS",
    EDITGROUP_ERROR: "EDITGROUP_ERROR",

    PAUSEGROUP: "PAUSEGROUP",
    PAUSEGROUP_SUCCESS: "PAUSEGROUP_SUCCESS",
    PAUSEGROUP_ERROR: "PAUSEGROUP_ERROR",

    FIND_GROUP: 'FIND_GROUP',
    FIND_GROUP_SUCCESS: 'FIND_GROUP_SUCCESS',
    FIND_GROUP_ERROR: 'FIND_GROUP_ERROR',

    CUSTOMER_GROUP: 'CUSTOMER_GROUP',
    CUSTOMER_GROUP_SUCCESS: 'CUSTOMER_GROUP_SUCCESS',
    CUSTOMER_GROUP_ERROR: 'CUSTOMER_GROUP_ERROR',

    JOIN_GROUP: 'JOIN_GROUP',
    JOIN_GROUP_SUCCESS: 'JOIN_GROUP_SUCCESS',
    JOIN_GROUP_ERROR: 'JOIN_GROUP_ERROR',

    SCHEDULE_CONTRIBUTION: 'SCHEDULE_CONTRIBUTION',
    SCHEDULE_CONTRIBUTION_SUCCESS: 'SCHEDULE_CONTRIBUTION_SUCCESS',
    SCHEDULE_CONTRIBUTION_ERROR: 'SCHEDULE_CONTRIBUTION_ERROR', 

    DELETE_MEMBER: 'DELETE_MEMBER',
    DELETE_MEMBER_SUCCESS: 'DELETE_MEMBER_SUCCESS',
    DELETE_MEMBER_ERROR: 'DELETE_MEMBER_ERROR',

    CASHOUT: 'CASHOUT',
    CASHOUT_SUCCESS: 'CASHOUT_SUCCESS',
    CASHOUT_ERROR: 'CASHOUT_ERROR',

    CONTINUE_SCHEDULEGROUP_PAYMENT: 'CONTINUE_SCHEDULEGROUP_PAYMENT',
    CONTINUE_SCHEDULEGROUP_PAYMENT_SUCCESS: 'CONTINUE_SCHEDULEGROUP_PAYMENT_SUCCESS',
    CONTINUE_SCHEDULEGROUP_PAYMENT_ERROR: 'CONTINUE_SCHEDULEGROUP_PAYMENT_ERROR',

    GROUPSAVINGS_STARTDATE: 'GROUPSAVINGS_STARTDATE',
    GROUPSAVINGS_ENDATE: 'GROUPSAVINGS_ENDATE',
    SETAMOUNT_TO_WITHDRAW: 'SETAMOUNT_TO_WITHDRAW',
    SET_FREQUENCY: 'SET_FREQUENCY',

    //ROTATING GROUP (ESUSU)

    CREATE_ROTATING_GROUP: 'CREATE_ROTATING_GROUP',
    CREATE_ROTATING_GROUP_SUCCESS: 'CREATE_ROTATING_GROUP_SUCCESS',
    CREATE_ROTATING_GROUP_ERROR: 'CREATE_ROTATING_GROUP_ERROR',

    ROTATING_GROUP_DETAILS: 'ROTATING_GROUP_DETAILS',
    ROTATING_GROUP_DETAILS_SUCCESS: 'ROTATING_GROUP_DETAILS_SUCCESS',
    ROTATING_GROUP_DETAILS_ERROR: 'ROTATING_GROUP_DETAILS_ERROR'

}

 































