export const IS_FETCHING_TRUE = 'IS_FETCHING_TRUE';
export const IS_FETCHING_FALSE = 'IS_FETCHING_FALSE';
export const IS_FETCHING_LOAN_TRUE = 'IS_FETCHING_LOAN_TRUE';
export const IS_FETCHING_LOAN_FALSE = 'IS_FETCHING_LOAN_FALSE';

export const FETCH_ACTIVE_LOANS_SUCCESS = 'FETCH_ACTIVE_LOANS_SUCCESS';
export const SET_LOAN_TO_LIQUIDATE = 'SET_LOAN_TO_LIQUIDATE';

export const CLEAR_LOAN_INFO  = 'CLEAR_LOAN_INFO';