export const IS_FETCHING_TRUE = 'IS_FETCHING_TRUE';
export const IS_FETCHING_FALSE = 'IS_FETCHING_FALSE';
export const IS_FETCHING_LOAN_TRUE = 'IS_FETCHING_LOAN_TRUE';
export const IS_FETCHING_LOAN_FALSE = 'IS_FETCHING_LOAN_FALSE';

export const FETCH_ACTIVE_LOANS_SUCCESS = 'FETCH_ACTIVE_LOANS_SUCCESS';
export const SET_LOAN_TO_LIQUIDATE = 'SET_LOAN_TO_LIQUIDATE';
export const SET_LOAN_DETAIL = 'SET_LOAN_DETAIL';

export const CLEAR_LOAN_INFO  = 'CLEAR_LOAN_INFO';

export const RESET_PAGE_STATE = 'RESET_PAGE_STATE';

export const LOAN_REPAID_SUCCESS = 'LOAN_REPAID_SUCCESS';
export const RESET_JOURNEY = 'RESET_JOURNEY';

export const GET_LOAN_STATE_SUCCESS = 'GET_LOAN_STATE_SUCCESS';
export const GET_LOAN_OFFERS_SUCCESS = 'GET_LOAN_OFFERS_SUCCESS';

export const SEND_LOAN_FOR_OTP_SUCCESS = 'SEND_LOAN_FOR_OTP_SUCCESS';
export const SEND_LOAN_WITH_OTP_SUCCESS = 'SEND_LOAN_WITH_OTP_SUCCESS';
