export const IS_FETCHING_TRUE  = 'IS_FETCHING_TRUE';
export const IS_FETCHING_FALSE = 'IS_FETCHING_FALSE';

export const CHANGE_PIN_SUCCESS = 'CHANGE_PIN_SUCCESS';
export const RESET_PAGE_STATE = 'RESET_PAGE_RESET';
export const CLEAR_CHANGE_PIN_DATA = 'CLEAR_CHANGE_PIN_DATA';

export const STORE_INFO = 'STORE_INFO';

export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
export const GET_QUESTION_SUCCESS_FORGOT = 'GET_QUESTION_SUCCESS_FORGOT';
export const CHANGE_PIN_ANSWER_CORRECT = 'CHANGE_PIN_ANSWER_CORRECT';
export const FORGOT_PIN_ANSWER_CORRECT = 'FORGOT_PIN_ANSWER_CORRECT';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const RESET_PIN_SUCCESS = 'RESET_PIN_SUCCESS';
