export const IS_FETCHING_TRUE  = 'IS_FETCHING_TRUE';
export const IS_FETCHING_FALSE = 'IS_FETCHING_FALSE';

export const CHANGE_PIN_SUCCESS = 'CHANGE_PIN_SUCCESS';
export const RESET_PAGE_STATE = 'RESET_PAGE_RESET';

