//Western Union

export const LOADING_WESTERNUNION_COUNTRIES_SUCCESS = 'LOADING_WESTERNUNION_COUNTRIES_SUCCESS';
export const LOADING_WESTERNUNION_COUNTRIES_PENDING = 'LOADING_WESTERNUNION_COUNTRIES_PENDING';
export const LOADING_WESTERNUNION_COUNTRIES_FAILURE = 'LOADING_WESTERNUNION_COUNTRIES_FAILURE';


export const RECEIVING_WESTERNUNION_SUCCESS = 'RECEIVING_WESTERNUNION_SUCCESS';
export const RECEIVING_WESTERNUNION_PENDING = 'RECEIVING_WESTERNUNION_PENDING';
export const RECEIVING_WESTERNUNION_FAILURE = 'RECEIVING_WESTERNUNION_FAILURE';

export const WESTERNUNION_REDUCER_CLEAR = 'WESTERNUNION_REDUCER_CLEAR';