
export const talktoUsConstant = {
        TALK_TO_US_PENDING: 'TALK_TO_US_PENDING',
        TALK_TO_US_SUCCESS:'TALK_TO_US_SUCCESS',
        TALK_TO_US_FAILURE:'TALK_TO_US_FAILURE',

        REPORT_ERROR_PENDING:"REPORT_ERROR_PENDING",
        REPORT_ERROR_SUCCESS:"REPORT_ERROR_SUCCESS",
        REPORT_ERROR_FAILURE:"REPORT_ERROR_FAILURE",

        GET_BANK_BRANCHES_PENDING:"GET_BANK_LOCATOR_PENDING",
        GET_BANK_BRANCHES_SUCCESS:"GET_BANK_BRANCHES_SUCCESS",
        GET_BANK_BRANCHES_FAILURE:"GET_BANK_BRANCHES_FAILURE",

        GET_PAGE_DATA_PENDING:"GET_PAGE_DATA_PENDING",
        GET_PAGE_DATA_SUCCESS:"GET_PAGE_DATA_SUCCESS",
        GET_PAGE_DATE_FAILURE:"GET_PAGE_DATE_FAILURE",

        GET_BANK_LIST_PENDING:"GET_BANK_LIST_PENDING",
        GET_BANK_LIST_SUCCESS:"GET_BANK_LIST_SUCCESS",
        GET_BANK_LIST_FAILURE:"GET_BANK_LIST_FAILURE",


 }
 